// This file is part of Substrate.

// Copyright (C) 2022 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_babe
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-01-31, STEPS: `1`, REPEAT: 1, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/substrate
// benchmark
// --chain=dev
// --steps=1
// --repeat=1
// --pallet=pallet_babe
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --output=./frame/offences/src/weights.rs
// --template=.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_babe.
pub trait WeightInfo {
	fn report_equivocation_unsigned_without_hook() -> Weight;
	fn check_equivocation_proof(x: u32, ) -> Weight;
}

/// Weights for pallet_babe using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn report_equivocation_unsigned_without_hook() -> Weight {
		(932_000 as Weight)
	}
	fn check_equivocation_proof(_x: u32, ) -> Weight {
		(253_257_000 as Weight)
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn report_equivocation_unsigned_without_hook() -> Weight {
		(932_000 as Weight)
	}
	fn check_equivocation_proof(_x: u32, ) -> Weight {
		(253_257_000 as Weight)
	}
}
